### ISSUE TITLE
Option to return with error if any key is missing

### ISSUE THREAD

**Issue by mausch** [subfuzion/envtpl#3]
It would be great to have a flag that stops envtpl with an error if any keys are missing.

It seems it's just a matter of setting the [missingkey option](https://golang.org/pkg/text/template/#Template.Option) for the template (I just [applied that in my fork](https://github.com/mausch/envtpl/commit/61e3c7771ef1385246724474595df7f931297b6b))

PS thanks for this tool!

**Comment by memory** [comment]
https://github.com/subfuzion/envtpl/pull/4 addresses this; just waiting for approval. :)

**Comment by subfuzion** [comment]
Closed with #4 (thanks!)
